version: "3.9"

services:
  bestellsystem:
    image: ghcr.io/panda260/bestellsystem:main
    ports:
      - "3000:3000"
    environment:
      BESTELL_PASSWORD: "changeme"
      SESSION_SECRET: "replace-me"
