services:
  bestellsystem:
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      BESTELL_PASSWORD: "187hdj"
      SESSION_SECRET: "kugfsugfeogfds"
    volumes:
      - ./data:/app/data
      - .:/app
      - /app/node_modules
